panelapp/api/urls.py
##
## Copyright (c) 2016-2019 Genomics England Ltd.
##
## This file is part of PanelApp
## (see https://panelapp.genomicsengland.co.uk).
##
## Licensed to the Apache Software Foundation (ASF) under one
## or more contributor license agreements.  See the NOTICE file
## distributed with this work for additional information
## regarding copyright ownership.  The ASF licenses this file
## to you under the Apache License, Version 2.0 (the
## "License"); you may not use this file except in compliance
## with the License.  You may obtain a copy of the License at
##
##   http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing,
## software distributed under the License is distributed on an
## "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
## KIND, either express or implied.  See the License for the
## specific language governing permissions and limitations
## under the License.
##
from django.conf import settings
from django.urls import (
    include,
    path,
)
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from .permissions import ReadOnlyPermissions

schema_view = get_schema_view(
    openapi.Info(
        title="PanelApp API",
        default_version=settings.REST_FRAMEWORK["DEFAULT_VERSION"],
        description="PanelApp API",
        terms_of_service="https://panelapp.genomicsengland.co.uk/policies/terms/",
        contact=openapi.Contact(email="panelapp@genomicsengland.co.uk"),
        license=openapi.License(name="MIT License"),
    ),
    patterns=["api"],
    validators=["flex", "ssv"],
    public=True,
    permission_classes=(ReadOnlyPermissions,),
)

app_name = "api"
urlpatterns = [path("v1/", include("api.v1.urls", namespace="v1"))]

panelapp/panels/urls.py
##
## Copyright (c) 2016-2019 Genomics England Ltd.
##
## This file is part of PanelApp
## (see https://panelapp.genomicsengland.co.uk).
##
## Licensed to the Apache Software Foundation (ASF) under one
## or more contributor license agreements.  See the NOTICE file
## distributed with this work for additional information
## regarding copyright ownership.  The ASF licenses this file
## to you under the Apache License, Version 2.0 (the
## "License"); you may not use this file except in compliance
## with the License.  You may obtain a copy of the License at
##
##   http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing,
## software distributed under the License is distributed on an
## "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
## KIND, either express or implied.  See the License for the
## specific language governing permissions and limitations
## under the License.
##
from django.conf.urls import url
from django.views.generic import RedirectView

from .ajax_views import (
    ApproveEntityAjaxView,
    ApprovePanelAjaxView,
    ClearModeOfPathogenicityAjaxView,
    ClearPhoenotypesAjaxView,
    ClearPublicationsAjaxView,
    ClearSingleSourceAjaxView,
    ClearSourcesAjaxView,
    ClearTranscriptAjaxView,
    DeleteEntityAjaxView,
    DeleteEntityCommentAjaxView,
    DeleteEntityEvaluationAjaxView,
    DeletePanelAjaxView,
    GetEntityCommentFormAjaxView,
    RejectPanelAjaxView,
    SubmitEntityCommentFormAjaxView,
    UpdateEntityMOIAjaxView,
    UpdateEntityMOPAjaxView,
    UpdateEntityPhenotypesAjaxView,
    UpdateEntityPublicationsAjaxView,
    UpdateEntityRatingAjaxView,
    UpdateEntityTagsAjaxView,
)
from .enums import VALID_ENTITY_FORMAT
from .views import (
    ActivityListView,
    AdminUploadGenesView,
    AdminUploadPanelsView,
    AdminUploadReviewsView,
    AdminView,
    CompareGeneView,
    ComparePanelsView,
    CopyReviewsView,
    CreatePanelView,
    DownloadAllGenes,
    DownloadAllPanels,
    DownloadAllRegions,
    DownloadAllSTRs,
    DownloadPanelTSVView,
    DownloadPanelVersionTSVView,
    EntitiesListView,
    EntityDetailView,
    EntityReviewView,
    GeneDetailRedirectView,
    GenePanelSpanshotView,
    GenePanelView,
    MarkEntityReadyView,
    MarkGeneNotReadyView,
    OldCodeURLRedirect,
    PanelAddEntityView,
    PanelEditEntityView,
    PanelMarkNotReadyView,
    PanelsIndexView,
    PromotePanelView,
    RedirectGenesToEntities,
    UpdatePanelView,
)

app_name = "panels"

entity_types = "gene|str|region"
TYPE_PARAM = f"(?P<entity_type>({entity_types}))"
NAME_PARAM = f"(?P<entity_name>{VALID_ENTITY_FORMAT})"
PK_PARAM = "(?P<pk>[0-9]+)"
COMMENT_PK_PARAM = "(?P<comment_pk>[0-9]+)"

urlpatterns = [
    url(r"^$", PanelsIndexView.as_view(), name="index"),
    url(r"^compare/$", ComparePanelsView.as_view(), name="compare_panels_form"),
    url(
        r"^compare/(?P<panel_1_id>[0-9]+)/(?P<panel_2_id>[0-9]+)$",
        ComparePanelsView.as_view(),
        name="compare",
    ),
    url(
        r"^compare/(?P<panel_1_id>[0-9]+)/(?P<panel_2_id>[0-9]+)/(?P<gene_symbol>[\w\-]+)$",
        CompareGeneView.as_view(),
        name="compare_genes",
    ),
    url(
        r"^copy/(?P<panel_1_id>[0-9]+)/(?P<panel_2_id>[0-9]+)$",
        CopyReviewsView.as_view(),
        name="copy_reviews",
    ),
    url(rf"^{PK_PARAM}/$", GenePanelView.as_view(), name="detail"),
    url(rf"^{PK_PARAM}/update$", UpdatePanelView.as_view(), name="update"),
    url(rf"^{PK_PARAM}/promote$", PromotePanelView.as_view(), name="promote"),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/add$",
        PanelAddEntityView.as_view(),
        name="add_entity",
    ),
    url(rf"^{PK_PARAM}/delete$", DeletePanelAjaxView.as_view(), name="delete_panel"),
    url(rf"^{PK_PARAM}/reject$", RejectPanelAjaxView.as_view(), name="reject_panel"),
    url(
        rf"^{PK_PARAM}/approve$", ApprovePanelAjaxView.as_view(), name="approve_panel",
    ),
    url(
        rf"^{PK_PARAM}/download/(?P<categories>[0-4]+)/$",
        DownloadPanelTSVView.as_view(),
        name="download_panel_tsv",
    ),
    url(
        rf"^{PK_PARAM}/download_version/$",
        DownloadPanelVersionTSVView.as_view(),
        name="download_old_panel_tsv",
    ),
    url(
        rf"^{PK_PARAM}/{NAME_PARAM}/$",
        RedirectGenesToEntities.as_view(),
        name="redirect_previous_structure",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/$",
        GenePanelSpanshotView.as_view(),
        name="evaluation",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/edit$",
        PanelEditEntityView.as_view(),
        name="edit_entity",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/review$",
        EntityReviewView.as_view(),
        name="review_entity",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/mark_as_ready$",
        MarkEntityReadyView.as_view(),
        name="mark_entity_as_ready",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/mark_as_not_ready$",
        MarkGeneNotReadyView.as_view(),
        name="mark_entity_as_not_ready",
    ),
    # AJAX endpoints
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/delete$",
        DeleteEntityAjaxView.as_view(),
        name="delete_entity",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/approve$",
        ApproveEntityAjaxView.as_view(),
        name="approve_entity",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/clear_entity_sources$",
        ClearSourcesAjaxView.as_view(),
        name="clear_entity_sources",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/clear_entity_source/(?P<source>(.*))/$",
        ClearSingleSourceAjaxView.as_view(),
        name="clear_entity_source",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/clear_entity_phenotypes$",
        ClearPhoenotypesAjaxView.as_view(),
        name="clear_entity_phenotypes",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/clear_entity_transcript$",
        ClearTranscriptAjaxView.as_view(),
        name="clear_entity_transcript",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/clear_entity_publications$",
        ClearPublicationsAjaxView.as_view(),
        name="clear_entity_publications",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/clear_entity_mode_of_pathogenicity$",
        ClearModeOfPathogenicityAjaxView.as_view(),
        name="clear_entity_mode_of_pathogenicity",
    ),
    # AJAX Review endpoints
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/update_entity_tags/$",
        UpdateEntityTagsAjaxView.as_view(),
        name="update_entity_tags",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/update_entity_rating/$",
        UpdateEntityRatingAjaxView.as_view(),
        name="update_entity_rating",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/update_entity_moi/$",
        UpdateEntityMOIAjaxView.as_view(),
        name="update_entity_moi",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/update_entity_mop/$",
        UpdateEntityMOPAjaxView.as_view(),
        name="update_entity_mop",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/update_entity_phenotypes/$",
        UpdateEntityPhenotypesAjaxView.as_view(),
        name="update_entity_phenotypes",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/update_entity_publications/$",
        UpdateEntityPublicationsAjaxView.as_view(),
        name="update_entity_publications",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/delete_evaluation/(?P<evaluation_pk>[0-9]+)/$",
        DeleteEntityEvaluationAjaxView.as_view(),
        name="delete_evaluation_by_user",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/edit_comment/{COMMENT_PK_PARAM}/$",
        GetEntityCommentFormAjaxView.as_view(),
        name="edit_comment_by_user",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/submit_edit_comment/{COMMENT_PK_PARAM}/$",
        SubmitEntityCommentFormAjaxView.as_view(),
        name="submit_edit_comment_by_user",
    ),
    url(
        rf"^{PK_PARAM}/{TYPE_PARAM}/{NAME_PARAM}/delete_comment/{COMMENT_PK_PARAM}/$",
        DeleteEntityCommentAjaxView.as_view(),
        name="delete_comment_by_user",
    ),
    url(
        rf"^{PK_PARAM}/mark_not_ready$",
        PanelMarkNotReadyView.as_view(),
        name="mark_not_ready",
    ),
    url(
        r"^(?P<pk>[a-z0-9]{24})/(?P<uri>.*|$)",
        OldCodeURLRedirect.as_view(),
        name="old_code_url_redirect",
    ),
    url(r"^create/", CreatePanelView.as_view(), name="create"),
    url(r"^entities/$", EntitiesListView.as_view(), name="entities_list"),
    url(r"^genes/$", RedirectView.as_view(url="/panels/entities"), name="genes_list"),
    url(rf"^entities/{NAME_PARAM}$", EntityDetailView.as_view(), name="entity_detail",),
    url(rf"^genes/{NAME_PARAM}$", GeneDetailRedirectView.as_view(),),
    url(r"^activity/$", ActivityListView.as_view(), name="activity"),
    url(r"^admin/", AdminView.as_view(), name="admin"),
    url(r"^upload_genes/", AdminUploadGenesView.as_view(), name="upload_genes"),
    url(r"^download_genes/", DownloadAllGenes.as_view(), name="download_genes"),
    url(r"^download_strs/", DownloadAllSTRs.as_view(), name="download_strs"),
    url(r"^download_regions/", DownloadAllRegions.as_view(), name="download_regions"),
    url(r"^upload_panel/", AdminUploadPanelsView.as_view(), name="upload_panels"),
    url(r"^download_panel/", DownloadAllPanels.as_view(), name="download_panels"),
    url(r"^upload_reviews/", AdminUploadReviewsView.as_view(), name="upload_reviews"),
]

panelapp/panels/models/Level4Title.py
##
## Copyright (c) 2016-2019 Genomics England Ltd.
##
## This file is part of PanelApp
## (see https://panelapp.genomicsengland.co.uk).
##
## Licensed to the Apache Software Foundation (ASF) under one
## or more contributor license agreements.  See the NOTICE file
## distributed with this work for additional information
## regarding copyright ownership.  The ASF licenses this file
## to you under the Apache License, Version 2.0 (the
## "License"); you may not use this file except in compliance
## with the License.  You may obtain a copy of the License at
##
##   http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing,
## software distributed under the License is distributed on an
## "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
## KIND, either express or implied.  See the License for the
## specific language governing permissions and limitations
## under the License.
##
from django.contrib.postgres.fields import ArrayField
from django.db import models


class Level4Title(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    level3title = models.CharField(max_length=255)
    level2title = models.CharField(max_length=255)
    omim = ArrayField(models.CharField(max_length=255))
    orphanet = ArrayField(models.CharField(max_length=255))
    hpo = ArrayField(models.CharField(max_length=255))

    def __str__(self):
        return str(self.name)

    __hash__ = models.Model.__hash__

    def __eq__(self, other):
        if other == self.name:
            return True
        else:
            return False

    def dict_tr(self):
        return {
            "name": self.name,
            "description": self.description,
            "level3title": self.level3title,
            "level2title": self.level2title,
            "omim": self.omim,
            "orphanet": self.orphanet,
            "hpo": self.hpo,
        }

panelapp/panels/models/activity.py
##
## Copyright (c) 2016-2019 Genomics England Ltd.
##
## This file is part of PanelApp
## (see https://panelapp.genomicsengland.co.uk).
##
## Licensed to the Apache Software Foundation (ASF) under one
## or more contributor license agreements.  See the NOTICE file
## distributed with this work for additional information
## regarding copyright ownership.  The ASF licenses this file
## to you under the Apache License, Version 2.0 (the
## "License"); you may not use this file except in compliance
## with the License.  You may obtain a copy of the License at
##
##   http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing,
## software distributed under the License is distributed on an
## "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
## KIND, either express or implied.  See the License for the
## specific language governing permissions and limitations
## under the License.
##
from copy import deepcopy

from django.contrib.postgres.fields import JSONField
from django.core.serializers.json import DjangoJSONEncoder
from django.db import models
from django.db.models import Q
from model_utils.models import TimeStampedModel

from accounts.models import User

from .genepanel import GenePanel


class ActivityManager(models.Manager):
    def visible_to_public(self):
        """Return activities for all publicly visible panels"""

        qs = self.get_queryset()
        qs = qs.filter(
            Q(panel__status=GenePanel.STATUS.public)
            | Q(panel__status=GenePanel.STATUS.promoted)
        )
        return qs

    def visible_to_gel(self):
        """Return activities visible to GeL curators"""

        return self.get_queryset()


class Activity(TimeStampedModel):
    class Meta:
        ordering = ("-created",)

    objects = ActivityManager()

    panel = models.ForeignKey(GenePanel, on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    text = models.TextField()
    item_type = models.CharField(max_length=32, null=True)  # TODO (Oleg) change to Enum
    entity_type = models.CharField(max_length=32, null=True)
    entity_name = models.CharField(max_length=128, null=True)
    extra_data = JSONField(default=dict, encoder=DjangoJSONEncoder)

    @property
    def panel_version(self):
        return self.extra_data.get("panel_version")

    @property
    def panel_name(self):
        return self.extra_data.get("panel_name")

    @property
    def user_name(self):
        return self.extra_data.get("user_name")

    @classmethod
    def log(cls, user, panel_snapshot, text, extra_info):
        extra_data = deepcopy(extra_info)

        if user:
            extra_data["user_name"] = user.get_full_name()

        extra_data["panel_name"] = panel_snapshot.panel.name
        extra_data["panel_id"] = panel_snapshot.panel_id
        extra_data["panel_version"] = panel_snapshot.version

        if "entity_type" in extra_info:
            extra_data["item_type"] = "entity"
            extra_data["entity_type"] = extra_info["entity_type"]
            extra_data["entity_name"] = extra_info["entity_name"]
        else:
            extra_data["item_type"] = "panel"

        cls.objects.create(
            user=user,
            panel=panel_snapshot.panel,
            text=text,
            extra_data=extra_data,
            item_type=extra_data["item_type"],
            entity_type=extra_data.get("entity_type"),
            entity_name=extra_data.get("entity_name"),
        )

panelapp/panels/templates/panels/entity/edit_comment.html
{% load bootstrap3 %}
<form action="{% url 'panels:submit_edit_comment_by_user' panel_id entity_type entity_name comment_pk %}#your-review" method="post" class="form">
  {% csrf_token %}
  {% for field in edit_comment_form %}
    <span class="rm">{{ field.label_tag }}</span>
    <div class="add-label-margin">{% bootstrap_field field show_label=False %}</div>
  {% endfor %}
  <input type="submit" class="btn btn-info" value="Save Changes">
</form>

panelapp/panels/templates/panels/entity/entity_evaluation.html
{% load panel_helpers %}
<div class="panel-body">
  {% with user=ev.user %}
  <div class="add-bottom-margin">
    <h4 class="normal remove-top-margin add-label-margin">
      {{ user.first_name }} {{ user.last_name }} ({{ user.reviewer.affiliation }})
    </h4>
    {% if request.user.is_authenticated and request.user.reviewer.is_GEL %}
      <a href="mailto:{{ user.email }}" class="link-muted">{{ user.email }}</a>
    {% endif %}
  </div>

  {% if ev.rating %}
  <p>
    <span class="gel-banner {{ ev|evaluation_rating_class }}">{{ ev|evaluation_rating_name }}</span>
  </p>
  {% endif %}

  {% for comment in ev.comments.all %}
    <blockquote class="add-top-margin" id="comment_{{ comment.pk }}">
      {{ comment.comment|linebreaksbr|urlize }}
      <h6>Created: {{ comment.created|date:'DATETIME_FORMAT' }} {% if comment.last_updated %}| Last Modified: {{ comment.last_updated|date:'DATETIME_FORMAT' }} {% endif %}</h6>
      {% if comment.version %}<h6>Panel Version: {{ comment.version }}</h6>{% endif %}
      {% if request.user == user and panel and entity %}
        <a href="{% url "panels:edit_comment_by_user" panel.panel_id entity_type entity_name comment.pk %}" class="btn btn-default btn-xs" data-ajax="true" data-success="djangoAjaxHandler">Edit your comment</a>
        <a href="{% url "panels:delete_comment_by_user" panel.panel_id entity_type entity_name comment.pk %}" class="btn btn-default btn-xs" data-ajax="true" data-success="djangoAjaxHandler">Delete comment</a>
      {% endif %}
    </blockquote>
  {% endfor %}
  {% endwith %}

  {% if ev.moi %}
    <p>
      <strong>Mode of inheritance</strong><br>
      {{ ev.moi }}
    </p>
  {% endif %}

  {% if ev.phenotypes %}
    <p>
      <strong>Phenotypes</strong><br>
      {{ ev.phenotypes|join:"; " }}
    </p>
  {% endif %}

  {% if ev.publications %}
    <p>
      <strong>Publications</strong>
      <ul>
        {% for publication in ev.publications %}
          <li>{{ publication|pubmed_link|join:'' }}</li>
        {% endfor %}
      </ul>
    </p>
  {% endif %}

  {% if ev.mode_of_pathogenicity %}
    <p>
      <strong>Mode of pathogenicity</strong><br>
      {{ ev.mode_of_pathogenicity }}
    </p>
  {% endif %}

  {% if ev.current_diagnostic  %}
    <p>Variants in this {{ entity_type|upper }} are reported as part of current diagnostic practice</p>
  {% endif %}

  {% if ev.clinically_relevant %}
      <strong>Clinically Relevant</strong><br>
      <p>Interruptions in the repeated sequence are reported as part of standard diagnostic practise</p>
  {% endif %}
</div>

{% if ev.version or ev.original_panel %}
<div class="panel-footer">
  Created: {{ ev.created|date:'DATETIME_FORMAT' }}<br>
    {% if ev.last_updated %}Last Modified: {{ ev.last_updated|date:'DATETIME_FORMAT' }} {% endif %}<br>
  {% if ev.original_panel %}
      <strong>Copied from panel: </strong>{{ ev.original_panel }}
  {% elif ev.version %}
      <strong>Panel version: </strong>{{ ev.version }}
  {% endif %}
</div>
{% endif %}

panelapp/panels/templates/panels/entity/evaluate.html
{% load bootstrap3 %}
{% if request.user.is_authenticated and request.user.reviewer.is_verified %}
{% include "panels/entity/evaluation_form.html" %}
{% endif %}

<div id="evaluations">
  <h3>{{ entity.evaluation.all|length }} review{{entity.evaluation.all|pluralize}}</h3>

  {% for ev in entity.evaluation.all %}
    <div class="panel panel-default {% if request.user == ev.user %}panel-highlight{% endif %}">
      {% if request.user == ev.user %}
      <div class="panel-heading" id="your-review">
        {% if request.user == ev.user %}
          <a href="{% url "panels:delete_evaluation_by_user" panel.panel_id entity_type entity_name ev.pk %}" class="pull-right btn btn-default btn-xs" data-ajax="true" data-success="djangoAjaxHandler">Delete</a>
        {% endif %}
        <div class="panel-title">
          Your review
        </div>
      </div>
      {% endif %}
      {% include "panels/entity/entity_evaluation.html" with ev=ev %}
    </div>
  {% endfor %}
</div>

panelapp/panels/templates/panels/entity/evaluation_create.html
{% extends "default.html" %}
{% load static %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block content %}
<ol class="breadcrumb">
    <li>
        <a href="{% url 'panels:index' %}">Panels</a>
    </li>
    <li>
        <a href="{{ view.panel.get_absolute_url }}">
            {{ view.panel.level4title.name }}
        </a>
    </li>
    <li>
        <a href="{% url 'panels:evaluation' view.panel.panel.id entity_type entity_name %}">
            {{ entity_name }}
        </a>
    </li>
    <li class="active">
        Add review
    </li>
</ol>

<h1>
    {% block title %}Review {% if entity_type == 'gene' %}gene{% elif entity_type == 'str' %}STR{% elif entity_type == 'region' %}Region{% endif %}{% endblock %}
</h1>

{% if request.user.is_authenticated and request.user.reviewer.is_verified %}
    <form class="row add-top-margin remove-empty-array-val" id="evaluation-create" method="post">
        {% csrf_token %}
        <div class="col-md-8">
            <div class="well">
                <fieldset>
                    {% for field in form %}
                        <div class="form-group">
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <span class="label label-danger">{{ error|escape }}</span>
                                {% endfor %}
                            {% endif %}

                            {% if field.name == "mode_of_pathogenicity" %}
                                {{ field.label_tag }} <a data-toggle="modal" data-target="#model_of_path" ><i class="fa fa-question-circle"></i></a>
                            {% elif field.name == "Model_of_inheritance" %}
                                {{ field.label_tag }} <a data-toggle="modal" data-target="#moi" ><i class="fa fa-question-circle"></i></a>
                            {% elif field.name == "rating" %}
                                <hr />
                                <h4 class="add-label-margin">Review gene</h4>
                                <p class="text-muted">You can optionally include a review of this gene when you add it.</p>
                                {{ field.label_tag }}
                            {% elif field.name == "current_diagnostic" %}
                                {{ field.label_tag }} <a data-toggle="modal" data-target="#diagostic" ><i class="fa fa-question-circle"></i></a>
                            {% else %}
                                {{ field.label_tag }}
                            {% endif %}

                            {% bootstrap_field field show_label=False %}
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">Add review</button>
                </fieldset>
            </div>
        </div>
    </form>
    {{ form.media }}
    {% block modals %}
        {% include "panels/modals/rating.html" %}
        {% include "panels/modals/mode_of_path.html" %}
        {% include "panels/modals/diagnostic.html" %}
        {% include "panels/modals/mode_of_inheritance.html" %}
    {% endblock %}
{% endif %}
{% endblock %}

panelapp/panels/templates/panels/entity/evaluation_update.html
{% extends "default.html" %}
{% load static %}
{% load staticfiles %}

{% block content %}
<ol class="breadcrumb">
    <li>
        <a href="{% url 'panels:index' %}">Panels</a>
    </li>
    <li>
        <a href="{% url 'panels:detail' panel.pk  %}">
            {{ panel.level4title.name }}
        </a>
    </li>
    <li>
        <a href="{% url 'panels:evaluation' panel.pk entity_type entity_name  %}">
            {{ entity.name }}
        </a>
    </li>
    <li class="active">
        Review {{ entity.label }}
    </li>
</ol>

<h1>
    {% block title %}Review {{ entity.label }} in panel {{ panel.level4title.name }}{% endblock %}
</h1>

{% if request.user.is_authenticated and request.user.reviewer.is_verified %}
{% include "panels/entity/evaluation_form.html" %}
{% endif %}
{% endblock %}

panelapp/panels/templates/panels/entity/history.html
{% load panel_helpers %}
<h3>History <a href="{% url 'panels:activity' %}?panel={{ panel.panel.pk }}&entity={{ entity.name }}" class="btn btn-default">Filter Activity</a></h3>
{% for track in entity.track.all %}
  <div class="panel panel-default">
    <div class="panel-body">
      <span class="text-muted">{{ track.created|date }}, Gel status: {{ track.gel_status }}</span>
      <h4 class="remove-top-margin">{{ track.issue_type|human_issue_type }}</h4>
      {% with user=track.user %}
      <strong>{{ user.first_name }} {{ user.last_name }} ({{ user.reviewer.affiliation }})</strong>
      {% endwith %}
      <p>
        {{ track.issue_description }}
      </p>
    </div>
  </div>
{% endfor %}